### ISSUE TITLE
Complete support for generating a static version of the blog via wallflower

### ISSUE THREAD

**Issue by book** [xsawyerx/PearlBee#19]
The first part was done in Perl-Evozon/PearlBee#55.

The next step is to take out the `[% settings.static && '.html' %]` from the templates, and replace that by some `url_for` method call for the various objects.

**Comment by book** [comment]
One problem is that the commits listed in Perl-Evozon/PearlBee#55 are not in our `wip/new-endpoint-struct` branch.

**Comment by xsawyerx** [comment]
@book Didn't we finish and merge this in this fork?

**Comment by book** [comment]
I think that's exactly what happened in #20.
